/**
 * Exercises migrations/0002_seed_product_refs.sql — generated by
 * scripts/build-seed-migration.mjs from data/seed/products/*.md (issue
 * #9) — against a real Miniflare D1 binding, applied on top of
 * migrations/0001_init.sql via tests/helpers/test-env.ts's `migrations`
 * option.
 *
 * Ground truth (the expected alias set per product, including the H1
 * display name) is computed independently in this file, parsing the same
 * 34 source files and normalizing the same way the generator does,
 * rather than trusting the generator's own internal
 * assertNoAliasCollisions() to have caught everything silently — see
 * CLAUDE.md "Pin crypto and absence assertions to something outside the
 * code under test".
 *
 * Lives under tests/ rather than next to the parser/resolver because
 * nothing under src/** may reach into data/seed — see
 * tests/seed-corpus-isolation.test.ts and data/seed/README.md. Mirrors
 * the loading pattern in tests/refs/corpus.test.ts and
 * tests/refs/resolve-corpus.test.ts, with its own glob/parse (those files
 * are owned by #4 and #8 respectively, and not imported here).
 */
import { afterEach, describe, expect, it } from "vitest";
import { REF_CATEGORY_LABELS, type ProductRef } from "../../src/refs/model";
import { parseProductRefMarkdown } from "../../src/refs/parse";
import { normalizeAlias } from "../../src/refs/resolve";
import { TABLE_NAMES } from "../../src/db/schema";
import { createTestEnv, type TestEnvHandle } from "../helpers/test-env";
import migration0002 from "../../migrations/0002_seed_product_refs.sql?raw";

const sources = new Map(
  Object.entries(
    import.meta.glob("../../data/seed/products/*.md", { query: "?raw", import: "default", eager: true }),
  ).map(([path, markdown]): [string, string] => [path.replace(/^.*\/(.+)\.md$/, "$1"), markdown]),
);

const refs: ProductRef[] = [...sources.entries()]
  .map(([slug, markdown]) => parseProductRefMarkdown({ slug, markdown }))
  .sort((a, b) => a.slug.localeCompare(b.slug));

/**
 * Every product's own alias set, plus its H1 display name — the same
 * rule build-seed-migration.mjs applies (issue #9: #8's resolver
 * exact-matches before falling back to containment, so registering the
 * H1 is what makes ai-smatrix and oam-vca-expander resolve from their
 * own display name instead of colliding with a different product's
 * alias). Recomputed here rather than imported from the generator, so
 * this test does not just re-check the generator agrees with itself.
 */
function expectedAliasesFor(ref: ProductRef): string[] {
  return [...new Set([...ref.aliases, ref.displayName].map(normalizeAlias))];
}

describe("migrations/0002_seed_product_refs.sql", () => {
  let env: TestEnvHandle | undefined;

  afterEach(async () => {
    await env?.dispose();
    env = undefined;
  });

  it("finds the expected 34-file corpus to compute ground truth from", () => {
    expect(refs).toHaveLength(34);
  });

  it("seeds exactly 34 product_refs rows, one per corpus slug, with the expected category distribution", async () => {
    env = await createTestEnv({ migrations: [migration0002] });

    const result = await env.db
      .prepare(`SELECT slug, category FROM ${TABLE_NAMES.productRefs} ORDER BY slug`)
      .all<{ slug: string; category: string }>();

    expect(result.results.map((row) => row.slug)).toEqual(refs.map((ref) => ref.slug));

    // Explicit <string, string>: REF_CATEGORY_LABELS' values are literal
    // types, which would otherwise narrow this map's KEY type to those
    // three literals — and the label being looked up comes from a D1 row,
    // i.e. a plain string, which is exactly the lookup this test is for.
    const labelToKey = new Map<string, string>(
      Object.entries(REF_CATEGORY_LABELS).map(([key, label]) => [label, key]),
    );
    const counts: Record<string, number> = { general: 0, "general-diy": 0, small: 0 };
    for (const row of result.results) {
      const key = labelToKey.get(row.category);
      if (key === undefined) throw new Error(`unknown category label ${JSON.stringify(row.category)}`);
      counts[key] = (counts[key] ?? 0) + 1;
    }
    expect(counts).toEqual({ general: 22, "general-diy": 7, small: 5 });
  });

  it("seeds exactly one product_ref_versions row per product, all at version 1, source 'seed'", async () => {
    env = await createTestEnv({ migrations: [migration0002] });

    const result = await env.db
      .prepare(`SELECT slug, version, source FROM ${TABLE_NAMES.productRefVersions} ORDER BY slug`)
      .all<{ slug: string; version: number; source: string }>();

    expect(result.results.map((row) => row.slug)).toEqual(refs.map((ref) => ref.slug));
    expect(result.results.every((row) => row.version === 1)).toBe(true);
    expect(result.results.every((row) => row.source === "seed")).toBe(true);
  });

  it("registers every alias — including each H1 display name — mapped to exactly the corpus's own slug, with no cross-product collision", async () => {
    env = await createTestEnv({ migrations: [migration0002] });

    const result = await env.db
      .prepare(`SELECT alias_norm, slug FROM ${TABLE_NAMES.productRefAliases} ORDER BY alias_norm`)
      .all<{ alias_norm: string; slug: string }>();

    // Building this map is itself a check, not just fixture setup: a
    // `set()` for an alias_norm already claimed by a different slug below
    // means the corpus itself has a cross-product collision.
    const expected = new Map<string, string>();
    for (const ref of refs) {
      for (const aliasNorm of expectedAliasesFor(ref)) {
        const owner = expected.get(aliasNorm);
        if (owner !== undefined && owner !== ref.slug) {
          throw new Error(
            `corpus alias collision in test ground truth: ${aliasNorm} claimed by both ${owner} and ${ref.slug}`,
          );
        }
        expected.set(aliasNorm, ref.slug);
      }
    }

    const actual = new Map(result.results.map((row) => [row.alias_norm, row.slug]));
    expect(actual).toEqual(expected);

    // product_ref_aliases.alias_norm is a PRIMARY KEY, so this can only
    // fail if the query above returned something D1 itself would have
    // rejected — restated directly over the rows as a second, more
    // literal reading of "no alias collides across products".
    const seen = new Set<string>();
    for (const row of result.results) {
      expect(seen.has(row.alias_norm), `duplicate alias_norm row: ${row.alias_norm}`).toBe(false);
      seen.add(row.alias_norm);
    }
  });

  it("applying 0002 twice leaves every row count unchanged (every insert is ON CONFLICT DO NOTHING)", async () => {
    env = await createTestEnv({ migrations: [migration0002, migration0002] });
    const db = env.db;

    const counts = await Promise.all(
      [TABLE_NAMES.productRefs, TABLE_NAMES.productRefVersions, TABLE_NAMES.productRefAliases].map(
        async (table) => (await db.prepare(`SELECT COUNT(*) AS n FROM ${table}`).first<{ n: number }>())!.n,
      ),
    );

    const expectedAliasCount = new Set(refs.flatMap((ref) => expectedAliasesFor(ref))).size;
    expect(counts).toEqual([34, 34, expectedAliasCount]);
  });

  /**
   * Regression guard for a real defect found while implementing this
   * migration: tests/helpers/test-env.ts applies a migration by
   * collapsing every run of whitespace in each `;`-split statement to a
   * single space before exec() (D1's exec() splits on newlines, not
   * semicolons — see that file's doc comment). A body_md string literal
   * holding a raw embedded newline does not survive that collapse — two
   * paragraphs separated by a blank line come back as one space-joined
   * line, verified empirically during implementation.
   * build-seed-migration.mjs's sqlText() avoids this by encoding every
   * text value as char(10)-joined single-line literals instead of
   * embedding newline bytes. zudo-rail.md has several blank-line
   * paragraph breaks across its three sections, so this is a real
   * exercise of that encoding, not a vacuous one.
   */
  it("stores body_md byte-identical to the source file, including blank lines between paragraphs", async () => {
    env = await createTestEnv({ migrations: [migration0002] });

    const row = await env.db
      .prepare(`SELECT body_md FROM ${TABLE_NAMES.productRefs} WHERE slug = ?`)
      .bind("zudo-rail")
      .first<{ body_md: string }>();

    const original = sources.get("zudo-rail")!;
    expect(original).toContain("\n\n"); // otherwise this test would pass vacuously
    expect(row?.body_md).toBe(original);
  });
});
