/**
 * Generates src/policy/generated.ts from policy/reply-guidance.md.
 *
 * The Markdown file is the source of truth and is intentionally tracked; the
 * generated TypeScript is a build artifact and remains gitignored. Keeping
 * generation deterministic means every Worker build embeds exactly the
 * policy document that was reviewed in the branch.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "..", "..");
const POLICY_FILE = path.join(ROOT, "policy", "reply-guidance.md");
const OUTPUT_FILE = path.join(ROOT, "src", "policy", "generated.ts");

const policy = await readFile(POLICY_FILE, "utf8");
const generated = [
  "// Generated by `pnpm policy:build` from policy/reply-guidance.md. Do not hand-edit.",
  `export const POLICY_CONTENT = ${JSON.stringify(policy)} as const;`,
  "",
].join("\n");

await writeFile(OUTPUT_FILE, generated, "utf8");
console.log(`wrote ${OUTPUT_FILE} (${Buffer.byteLength(policy, "utf8")} bytes)`);
